blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/sebastian-software/effective-shadow/discussions
    about: For questions and discussions, please use GitHub Discussions.

